### ISSUE TITLE
[依頼] ChatSpace挙動確認

### ISSUE THREAD

**Issue by tech-yutaro** [tech-yutaro/chat-space#12]
# IPアドレス
3.114.198.76

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！


**○ 投稿した画像が表示されない**

![非同期通信画面](https://user-images.githubusercontent.com/44963290/77811085-64d43900-70db-11ea-9499-6f475e55619e.png)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tech-yutaro** [comment]
修正しました

**Comment by mo1015** [comment]
再提出ありがとうございます！

前回指摘箇所、**○ 投稿した画像が表示されない**について、
修正確認ができました！ありがとうございます！

もう2点、修正をお願いしたい箇所があります。
**○contents上部のグループ名の位置にズレがある**

↓見本のように位置を左に寄せましょう
<img width="249" alt="見本" src="https://user-images.githubusercontent.com/62644781/78956168-64e12980-7b1c-11ea-9099-5219936a1fa7.png">

○投稿フォームの「type a message」の文言が左に偏っている
<img width="1160" alt="スクリーンショット 2020-04-10 11 11 10" src="https://user-images.githubusercontent.com/62644781/78956201-83dfbb80-7b1c-11ea-88e1-6478d82cc9d1.png">

↓カリキュラムを参考に修正をお願いします
<img width="691" alt="スクリーンショット 2020-04-10 10 23 39" src="https://user-images.githubusercontent.com/62644781/78956316-dde08100-7b1c-11ea-991f-400f4fa36fb0.png">



確認でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tech-yutaro** [comment]
修正しました

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by tech-yutaro** [comment]
ありがとうございます！
